export const ANIMATION_DELAYS = {
    SHUFFLER_INTERVAL: 2800,
    TYPEWRITER_CHAR_DELAY: 38,
    CURSOR_STEP_DELAY: 350,
    CURSOR_INITIAL_DELAY: 800,
    CURSOR_SAVE_DELAY: 600,
    SEQUENCE_REPEAT_DELAY: 4000,
    SCHEDULER_SAVED_DELAY: 1200,
}

export const MODAL_DELAYS = {
    OVERLAY_FADE: 0.3,
    PANEL_FADE: 0.4,
    PANEL_SLIDE: 0.25,
    PANEL_DELAY: 0.1,
}

export const SCROLL_DELAYS = {
    NAV_HIDE: 80,
    TRIGGER_TOP_70: 'top 70%',
    TRIGGER_TOP_75: 'top 75%',
    TRIGGER_TOP_65: 'top 65%',
}